### ISSUE TITLE
macOS users need to download PyObjC

### ISSUE THREAD

**Issue by ouimet51** [pvcraven/arcade_book#4]
For mac users to utilize sounds in python arcade you need to have access to the cocoa framework (i'm not 100% sure why)I was able to work around this by downloading PyObjC... Users with pip installed can just run the following command. 

pip3 install PyObjC

P.S - Thanks so much for this book and library, I have been working through it and having a blast.

**Comment by pvcraven** [comment]
PyObjC is used to access the mac subsystem for playing sounds. Until we get ffmpeg support going, we are relying on that.
