### ISSUE TITLE
Mismatch betewen declared and used functions in chapter 8

### ISSUE THREAD

**Issue by FooDownunder** [pvcraven/arcade_book#5]
https://arcade-book.readthedocs.io/en/latest/chapters/08_functions/functions.html

```
def add_numbers(a, b):
    print(a, b)
print_number(11, 7)
```

the def and function call should be the same
However is the readthe docs the current version of this file in github?

**Comment by FooDownunder** [comment]
https://arcade-book.readthedocs.io/en/latest/chapters/08_functions/functions.html
However ... is the readthedocs.io the current version?

**Comment by pvcraven** [comment]
Thanks, should be fixed now.

And yes, GitHub and ReadTheDocs should always be synced.
